### ISSUE TITLE
Local Source for lpl-thumbnails-downloader.py

### ISSUE THREAD

**Issue by mspykerez** [Mte90/Script#5]
Is it possible to add an option to input a local path to search for Thumbnails as an alternative to download them from the internet ?

**Comment by Mte90** [comment]
The scope of my script was to use the official repo from retroarch that is a standard, it is better to contribute on adding new photos on them so all the users of retroarch can benefit.

Also I created the script for my usage and I don't want to support things outside because I cannot dedicate so much time on that.
